projects:
  app:
    # schemaPath: src/schema.graphql
    includes: ["**/*.graphql"]
    extensions:
      endpoints:
        default: http://localhost:3000
  db:
    # schemaPath: src/generated/db.graphql
    includes: ["**/*.graphql"]
    extensions:
      codegen:
        - generator: graphql-binding
          language: typescript
          output:
            binding: src/graphql.schema.ts
