version: "3.7"

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:debug
    environment:
      NODE_ENV: development
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - redis
      - mysql
  redis:
    container_name: redis
    image: redis:5
    ports:
      - 6379:6379
    networks:
      - webnet
  mysql:
    image: mysql:5.7
    networks:
      - webnet
    restart: always
    ports:
      - 3306:${DATABASE_PORT}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8MB4;' --sql-mode="NO_ENGINE_SUBSTITUTION" --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
networks:
  webnet:
